trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  VERACODE_API_KEY_ID: $(VeracodeApiId)
  VERACODE_API_KEY_SECRET: $(VeracodeApiKey)

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'app/pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    options: '-DskipTests=true -Dmaven.javadoc.skip=true'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/app/target'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/jars'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/jars'
    ArtifactName: 'jars'
    publishLocation: 'Container'

- task: Veracode Flaw Importer@3
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    veracodeAppProfile: '$(system.teamProject)'
    sandboxName: 
    scanType: 'SCA'
    importType: 'All Unmitigated Flaws Violating Policy'
    workItemType: 'Bug'
    area: '$(system.teamProject)'
    overwriteAreaPathInWorkItemsOnImport: true
    iterationPath: '$(system.teamProject)'
    overwriteIterationPath: true
    flawImportLimit: '1000'