
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  veracodeAppProfile: '$(APP_PROFILE)' # This assumes APP_PROFILE is a variable defined in the pipeline settings

stages:
- stage: Build
  displayName: 'Build and Scan'
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building the project...

    - task: Veracode@3
      inputs:
        ConnectionDetailsSelection: 'Credentials'
        apiId: '389348b563b0eec8bb02992541e6847c'
        apiKey: 'f0c49aba9d5a422605b3023defeb08247d0afa95cf27384d9a46328ba9bdcf2f68f18264776cf16c0656a4dd65fe963628d6d9ff235c8cc5dab51b6d562dbb33'
        veracodeAppProfile: '$(system.teamProject)'
        version: '$(build.buildNumber)'
        filepath: '$(build.artifactstagingdirectory)'
        importResults: true
        maximumWaitTime: '360'